// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreateUserInput struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Role      string `json:"role"`
	Password  string `json:"password"`
}

type UpdateUserInput struct {
	Username  *string `json:"username"`
	Email     *string `json:"email"`
	Firstname *string `json:"firstname"`
	Role      *string `json:"role"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Role      string `json:"role"`
}
